### ISSUE TITLE
Error no matter the start prompt

### ISSUE THREAD

**Issue by Kallamamran** [TheCompAce/Auto-GPT-Powershell#8]
Hash: bd89e826cf21de3dd0272ebaeb7dbaf69038dd26 (2013-04-19)

```
Debug: Prompt:
Debug: Response:
Sort-Object : A parameter cannot be found that matches parameter name 'Depth'.
At Q:\Auto-GPT-Powershell\module\General.ps1:66 char:59
+ ... luginType | Sort-Object { (GetProperty -properties (& $_.FullName -Fu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (Output_CodeSaver.ps1:PSObject) [Sort-Object], ParameterBindingException
    + FullyQualifiedErrorId : ExpressionEvaluation,Microsoft.PowerShell.Commands.SortObjectCommand

Sort-Object : A parameter cannot be found that matches parameter name 'Depth'.
At Q:\Auto-GPT-Powershell\module\General.ps1:66 char:59
+ ... luginType | Sort-Object { (GetProperty -properties (& $_.FullName -Fu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (Output_SessionLog.ps1:PSObject) [Sort-Object], ParameterBindingException
    + FullyQualifiedErrorId : ExpressionEvaluation,Microsoft.PowerShell.Commands.SortObjectCommand

ConvertFrom-Json : A parameter cannot be found that matches parameter name 'Depth'.
At Q:\Auto-GPT-Powershell\module\General.ps1:103 char:72
+ ... uginsJson = Get-Content $pluginsJsonPath | ConvertFrom-Json -Depth 10
+                                                                 ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ConvertFrom-Json], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

ConvertFrom-Json : A parameter cannot be found that matches parameter name 'Depth'.
At Q:\Auto-GPT-Powershell\module\General.ps1:103 char:72
+ ... uginsJson = Get-Content $pluginsJsonPath | ConvertFrom-Json -Depth 10
+                                                                 ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [ConvertFrom-Json], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.Commands.ConvertFromJsonCommand
```

**Comment by TheCompAce** [comment]
It looks like, maybe, you need to delete your plugins file, but if you do then you need to go threw and enable the SessionLog plugin or else it will not write the session file.

**Comment by Kallamamran** [comment]
Hmmm... Now it did this... 👍
![image](https://user-images.githubusercontent.com/25354644/233031477-374b3490-68fa-46c5-86e4-e587386c4a44.png)

**Comment by TheCompAce** [comment]
Ok I got it fixed, try to delete the plugins.json and try again. But as of now, I need some sleep.

**Comment by Kallamamran** [comment]
I have deleted the json-file, but it still doesn't do much. It does something though 🤔

![image](https://user-images.githubusercontent.com/25354644/233034264-4afaa4da-0976-4757-b5f5-0e72ffe6b0e6.png)

![image](https://user-images.githubusercontent.com/25354644/233034661-81a2770d-83ad-4b60-883c-128c566b628f.png)

Sleep tight! I'll monitor this repo for sure 👍🏻

**Comment by TheCompAce** [comment]
I have changed this so the properties update automatically so you want have to delete the plugins.json file. (If you need to clear a plugins properties you can open it in a JSON editor and delete the section with the "FullName" property of the plugin you want to delete.)  Regardless a update should be coming soon. I will mark this as complete once I update the code, if you have another problem please start a new issue.

**Comment by TheCompAce** [comment]
Code Updated. Might need to think of a versioning system.

**Comment by Kallamamran** [comment]
I don't get errors any more, but I don't know how to use it to generate... Well... Anything...
No matter the starting prompt I write I get nothing back. It just loops through 5 times of nothing

**Comment by TheCompAce** [comment]
When you first start it, lick "y" to goto the options, and "Turn On Debug" ad the Debug Messages show up, I am adding text to show you where in the loop it is and what it is doing. But when it is done running there should be a:Sassion" folder and in there will be the data that was generated.

**Comment by Kallamamran** [comment]
I have debug on and do get a sessions-folder, but the output file only shows this
```

System: 
Prompt: 
Response: 
System: 
Prompt: 
Response: 
System: 
Prompt: 
Response: 
System: 
Prompt: 
Response: 
System: 
Prompt: 
Response: 

```

**Comment by TheCompAce** [comment]
OK, I will be working on finishing up a couple things tonight, and I will add this to the list. Did you use the "Setup .." menus?
Also if you could send me what the "Advance Options" look like, I can tell you what is going on.

**Comment by Kallamamran** [comment]
I did use the Setup menu
![image](https://user-images.githubusercontent.com/25354644/234116063-a54a07b7-0cb9-462c-972f-149cccf72c3a.png)
Not sure what you mean by "advanced options"
![image](https://user-images.githubusercontent.com/25354644/234116250-88f1b644-8a18-4599-8e03-a5335f31e222.png)

**Comment by TheCompAce** [comment]
Do you have "gpt4all-lora-quantized.bin" in the same folder as "gpt4all-lora-quantized-win64.exe"?  I am also making it to use "StableLM-Tuned-Alpha-7b Chat" (if your PC can handle it, I can run it with very basic settings, so it will not work on my PC, but maybe someone wout there will have one strong enough to test it. So the GPT4ALL model is going to be replaced, because it does not work, it response with responses that seem off topic, and do not follow the prompt sent to it.  So to really use this, OpenAI is the only thing so far, when I wrap up the code I am doing, it will have a Text To Image (using DALLE or local Stable Diffusion) and Bark (for creating speech from text) Hopefully I can get this wrapped up tonight, I am just caught doing work for my job.

**Comment by Kallamamran** [comment]
I have the model in the same folder yes. I can run it separatedly through the exe.
The StableLM-Tuned-Alpha-7b model is really bad. Lol!
Sounds like your plans are on the right track :) SD and Bark is great. DallE is to expensive.
